feat: allow custom exit command implementation
hongaar/bandersnatch pull request #275
Opened 2021-07-28 16:51 UTC by axelrindle

I'm creating a CLI which runs in an async context with init and dispose hooks. Just calling `process.exit()` when the user types `exit` may be fatal.

This change allows for custom implementation for an `exit` command.

2021-07-28 20:25 UTC, hongaar commented
Thanks for creating this PR. I'm in favour of such a change.

I suggest a slightly different implementation though: make this option part of the global options passed to the `Program` constructor. Let's just call it `exit` to align better with the existing `help` and `version` options. What about it could take `false` or a function as value and defaults to `() => process.exit()`, would that work for your use case?

2021-07-28 20:27 UTC, axelrindle commented
> I suggest a slightly different implementation though...

Got it. Will implement this tomorrow.

> What about it could take false or a function as value and defaults to () => process.exit(), would that work for your use case?

Yes. I will add that.

2021-07-29 17:02 UTC, axelrindle commented
Ok, everything should be implemented now.

2021-07-29 17:14 UTC, hongaar requested changes
Looks good to me, can you address the comment and add a description to the README? Then it's good to go. (If you can, a test for this would be appreciated)

2021-07-29 17:14 UTC, hongaar commented on src/program.ts
> +    if (this.options.exit && typeof this.options.exit !== 'function') {
When `this.options.exit` is set to `true` it doesn't set the default value.
```suggestion
    if (this.options.exit === true || typeof this.options.exit === 'undefined') {
```

2021-07-29 17:46 UTC, axelrindle commented
I'm not familiar with `jest`, I suggest you add that test 😅

2021-07-29 21:29 UTC, hongaar approved these changes
Thanks for the PR!

2021-07-29 21:30 UTC, merged

2021-07-29 21:46 UTC, hongaar commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/bandersnatch/v/1.7.0)
- [GitHub release](https://github.com/hongaar/bandersnatch/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: